-- MySQL Script generated by MySQL Workbench
-- Thu Jul 20 13:15:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema greenvibes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema greenvibes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `greenvibes` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `greenvibes` ;

-- -----------------------------------------------------
-- Table `greenvibes`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenvibes`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(125) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(225) NOT NULL,
  `birthday` DATE NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `address` VARCHAR(125) NOT NULL,
  `profession` VARCHAR(125) NULL,
  `schooling_level` VARCHAR(125) NULL,
  `gender` VARCHAR(45) NULL,
  `race` VARCHAR(45) NULL,
  `image` BLOB NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenvibes`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenvibes`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `dimensions` VARCHAR(45) NULL,
  `year` YEAR NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `type` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `materials` VARCHAR(125) NULL,
  `weight` DOUBLE ZEROFILL NULL,
  `price` DOUBLE ZEROFILL NOT NULL,
  `image` BLOB NULL,
  `stock` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_products_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `greenvibes`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenvibes`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenvibes`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `payment_method` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenvibes`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenvibes`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_init` DATE NOT NULL,
  `date_end` DATE NOT NULL,
  `users_id` INT NOT NULL,
  `payment_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `payment_id`),
  INDEX `fk_order_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_order_payment1_idx` (`payment_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `greenvibes`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_payment1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `greenvibes`.`payment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenvibes`.`account_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenvibes`.`account_session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total` DECIMAL(0) NULL,
  `login_time` TIMESTAMP NULL,
  `logout_time` TIMESTAMP NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_account_session_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_session_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `greenvibes`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenvibes`.`cart_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenvibes`.`cart_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `added` DATETIME NULL,
  `account_session_id` INT NOT NULL,
  `account_session_users_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `products_users_id` INT NOT NULL,
  `quantity` INT ZEROFILL NULL,
  PRIMARY KEY (`id`, `account_session_id`, `account_session_users_id`, `products_id`, `products_users_id`),
  INDEX `fk_cart_items_account_session1_idx` (`account_session_id` ASC, `account_session_users_id` ASC) VISIBLE,
  INDEX `fk_cart_items_products1_idx` (`products_id` ASC, `products_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_items_account_session1`
    FOREIGN KEY (`account_session_id` , `account_session_users_id`)
    REFERENCES `greenvibes`.`account_session` (`id` , `users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_items_products1`
    FOREIGN KEY (`products_id` , `products_users_id`)
    REFERENCES `greenvibes`.`products` (`id` , `users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenvibes`.`order_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenvibes`.`order_has_products` (
  `order_item_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `quantity` INT ZEROFILL NULL,
  `total` DECIMAL ZEROFILL NULL,
  PRIMARY KEY (`order_item_id`, `products_id`),
  INDEX `fk_order_item_has_products_products1_idx` (`products_id` ASC) VISIBLE,
  INDEX `fk_order_item_has_products_order_item1_idx` (`order_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_item_has_products_order_item1`
    FOREIGN KEY (`order_item_id`)
    REFERENCES `greenvibes`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_item_has_products_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `greenvibes`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
